[build]
  publish = "."
  command = "echo 'Static HTML - no build needed!'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "microphone=(self)"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
